### ISSUE TITLE
2.4.0 Release checklist

### ISSUE THREAD

**Issue by yaakov-h** [SteamRE/SteamKit#1051]
- [x] https://github.com/SteamRE/SteamKit/pull/1049
- [x] https://github.com/SteamRE/SteamKit/pull/1050
- [x] https://github.com/SteamRE/SteamKit/pull/1036
- [x] https://github.com/SteamRE/SteamKit/pull/1022
- [ ] ~https://github.com/SteamRE/SteamKit/issues/1057~
- [x] Draft/update release notes, including any breaking changes from .NET 6 PR
  - https://github.com/SteamRE/SteamKit/pull/1058
- [x] Update tag / url / etc.
  - https://github.com/SteamRE/SteamKit/pull/1058
- [x] https://github.com/SteamRE/SteamKit/pull/1059
- [x] Release 2.4.0-Beta.1.
- [x] Wait 14 days for issue reports.
- [x] Merge Alpha/Beta release notes into new 2.4.0 release notes section.
  - https://github.com/SteamRE/SteamKit/pull/1064
- [x] Release 2.4.0.
- [x] Set the new [base version](https://github.com/SteamRE/SteamKit/blob/master/Directory.Build.props#L4) to 2.5.0

**Comment by yaakov-h** [comment]
Trimming is blocked by https://github.com/dotnet/linker/issues/2365 at the moment.

**Comment by yaakov-h** [comment]
Note to self: Add #1062 to update notes

**Comment by yaakov-h** [comment]
Note: Add 2ef0773 to update notes (no PR)
