### ISSUE TITLE
Transition IRC channel to Freenode

### ISSUE THREAD

**Issue by VoiDeD** [SteamRE/SteamKit#846]
Just a small checklist of things we'd need during the transition of our IRC channel from GameSurge to Freenode.

- [x] Decide on a new name (candidates so far being #steamre, and #steamkit - just keep in mind a similarity to #steamdb that might annoy some people).
- [x] Update readme.md
- [x] Wiki has an IRC etiquette section, needs to be updated if it's referencing the gamesurge channel
- [x] Configure chanserv on GS with a welcome message to inform users we've moved
- [x] Update channel title to inform users we've moved
- [x] @xPaw can update Wendy's github notifications to point them to the new channel
- [ ] Temporary chat relay bot? (more of a wishlist thing)

I'm probably forgetting things but this seems like the bulk of the stuff we'd want to update.

**Comment by xPaw** [comment]
Travis configs need changing: https://github.com/search?q=org%3ASteamRE+gamesurge&type=Code

On wiki, I only see it listed on the home page.

**Comment by VoiDeD** [comment]
We've decided on #steamkit. I've also updated the TODO list with what's been completed so far.

**Comment by yaakov-h** [comment]
@VoiDeD with everything done but a relay, can we close this?

**Comment by VoiDeD** [comment]
@yaakov-h yup, the relay bot seems unnecessary so we can consider this complete.
